data_name: ["BabyAI-GoToSeq-v0", "BabyAI-GoToRedBall-v0", "BabyAI-GoToObj-v0"]
env_name: ["BabyAI-GoToSeq-v0", "BabyAI-GoToRedBall-v0", "BabyAI-GoToObj-v0"]
pct_traj: 1.0
K: 20
batch_size: 64
max_ep_len: 1000
step_num: 5000000